# Generated by Django 5.2.8 on 2025-11-20 16:13

import pictures.models
from django.db import migrations

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0016_alter_post_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="logo",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="logo_height",
                max_length=255,
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
                width_field="logo_width",
            ),
        ),
    ]
