# Generated by Django 5.2.8 on 2025-11-20 16:13

import pictures.models
from django.db import migrations, models

import grandchallenge.challenges.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0060_alter_challenge_banner_alter_challenge_logo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="banner",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="banner_height",
                help_text="Image that gets displayed at the top of each page. Recommended resolution 2200x440 px.",
                max_length=255,
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_banner_path,
                width_field="banner_width",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="logo",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="logo_height",
                help_text="A logo for this challenge. Should be square with a resolution of 640x640 px or higher.",
                max_length=255,
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
                width_field="logo_width",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="social_image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="social_image_height",
                help_text="An image for this challenge which is displayed when you post the link on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                max_length=255,
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
                width_field="social_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="structured_challenge_submission_form",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.challenges.models.submission_pdf_path,
                validators=[
                    grandchallenge.core.validators.ExtensionValidator(
                        allowed_extensions=(".pdf",)
                    ),
                    grandchallenge.core.validators.MimeTypeValidator(
                        allowed_types=("application/pdf",)
                    ),
                ],
            ),
        ),
    ]
