# Generated by Django 5.2.8 on 2025-11-20 16:13

from django.db import migrations, models

import grandchallenge.cases.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_dicomimagesetuploadgroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.cases.models.image_file_path,
            ),
        ),
    ]
