# Generated by Django 5.2.8 on 2025-11-27 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_alter_imagefile_file"),
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "uploads",
            "0009_useruploadgroupobjectpermission_uploads_use_group_i_53998e_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="linked_object_content_type",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dicomimagesetupload_linked_object",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="linked_object_object_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="linked_socket_slug",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="dicomimagesetupload",
            index=models.Index(
                fields=[
                    "linked_object_content_type",
                    "linked_object_object_id",
                ],
                name="cases_dicom_linked__22fe01_idx",
            ),
        ),
    ]
