# Generated by Django 5.2.8 on 2025-12-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0026_dicomimagesetupload_linked_object_content_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="patient_age",
            field=models.CharField(
                blank=True, default="", max_length=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="patient_id",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="patient_name",
            field=models.CharField(
                blank=True, default="", max_length=324, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="patient_sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="series_description",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="series_instance_uid",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="study_description",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="study_instance_uid",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True
            ),
        ),
    ]
