# Generated by Django 5.2.8 on 2025-11-20 16:13

from django.db import migrations, models

import grandchallenge.core.storage
import grandchallenge.github.models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0008_auto_20220201_1203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubwebhookmessage",
            name="zipfile",
            field=models.FileField(
                max_length=255,
                null=True,
                storage=grandchallenge.core.storage.PrivateS3Storage(),
                upload_to=grandchallenge.github.models.zipfile_path,
            ),
        ),
    ]
