# Generated by Django 5.2.8 on 2025-11-20 16:13

from django.db import migrations, models

import grandchallenge.components.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0026_alter_componentinterface_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinterfacevalue",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.components.models.component_interface_value_path,
                validators=[
                    grandchallenge.core.validators.ExtensionValidator(
                        allowed_extensions=(
                            ".json",
                            ".zip",
                            ".csv",
                            ".png",
                            ".jpg",
                            ".jpeg",
                            ".pdf",
                            ".sqreg",
                            ".obj",
                            ".mp4",
                            ".newick",
                            ".biom",
                        )
                    ),
                    grandchallenge.core.validators.MimeTypeValidator(
                        allowed_types=(
                            "application/json",
                            "application/zip",
                            "text/plain",
                            "application/csv",
                            "text/csv",
                            "application/pdf",
                            "image/png",
                            "image/jpeg",
                            "application/octet-stream",
                            "application/x-sqlite3",
                            "application/vnd.sqlite3",
                            "video/mp4",
                        )
                    ),
                ],
            ),
        ),
    ]
