# Generated by Django 5.2.8 on 2025-11-20 16:13

import pictures.models
from django.db import migrations, models

import grandchallenge.algorithms.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0087_alter_algorithmimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="logo",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="logo_height",
                max_length=255,
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
                width_field="logo_width",
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="social_image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="social_image_height",
                help_text="An image for this algorithm which is displayed when you post the link for this algorithm on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                max_length=255,
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
                width_field="social_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="algorithmmodel",
            name="model",
            field=models.FileField(
                blank=True,
                help_text=".tar.gz file of the algorithm model that will be extracted to /opt/ml/model/ during inference",
                max_length=255,
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.algorithms.models.algorithm_models_path,
                validators=[
                    grandchallenge.core.validators.ExtensionValidator(
                        allowed_extensions=(".tar.gz",)
                    )
                ],
            ),
        ),
    ]
