# Generated by Django 5.2.17 on 2026-10-02 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0104_alter_job_algorithm_interface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="time_limit",
            field=models.PositiveIntegerField(
                help_text="Time limit in seconds for a single inference task (one invocation)",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=300),
                    django.core.validators.MaxValueValidator(
                        limit_value=86400
                    ),
                ],
            ),
        ),
    ]
