# Generated by Django 5.2.8 on 2025-11-20 16:13

import pictures.models
from django.db import migrations

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0024_alter_userprofile_mugshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mugshot",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="mugshot_height",
                help_text="A personal image displayed in your profile.",
                max_length=255,
                pixel_densities=[1, 2],
                upload_to=grandchallenge.core.storage.get_mugshot_path,
                verbose_name="mugshot",
                width_field="mugshot_width",
            ),
        ),
    ]
